import os
from datetime import datetime

from flask import Flask, request, jsonify
from twilio.rest import Client

from sheets import (
    add_subscriber,
    get_all_subscribers,
    save_daily_transcription,
    get_latest_transcription,
)
from sms import send_sms
from emailer import send_email

app = Flask(__name__)

# Environment / config
TWILIO_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_FROM = os.getenv("TWILIO_FROM_NUMBER")  # your Twilio number: +12568011212

# Huntsville Municipal Court Probation color code recording line
HUNTSVILLE_COLOR_LINE = "+12564277808"

# Optional: base URL of this service (for Twilio callbacks)
BASE_URL = os.getenv("APP_BASE_URL")  # e.g. https://colorcodely-carrdco-backend.onrender.com

twilio_client = Client(TWILIO_SID, TWILIO_AUTH) if (TWILIO_SID and TWILIO_AUTH) else None


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


def _get_request_data():
    """
    Carrd typically sends application/x-www-form-urlencoded, but we also support JSON.
    Returns a dict-like object.
    """
    data = request.get_json(silent=True)
    if data is None:
        data = request.form
    return data


@app.route("/submit", methods=["POST"])
def submit():
    """
    New subscriber signup endpoint.

    Expects fields (from Carrd):
      - full_name
      - email
      - cell_number
      - testing_center

    Behavior:
      1. Save subscriber in Google Sheet (Subscribers tab)
      2. Look up latest transcription for today (if any)
      3. Send welcome email + SMS including today's transcription text (if available)
    """
    try:
        data = _get_request_data()

        full_name = data.get("full_name")
        email = data.get("email")
        cell_number = data.get("cell_number")
        testing_center = data.get("testing_center")

        if not (full_name and email and cell_number and testing_center):
            return jsonify({"status": "error", "message": "Missing required fields"}), 400

        # 1) Save subscriber
        add_subscriber(full_name, email, cell_number, testing_center)

        # 2) Get latest transcription (if any)
        date_str, transcription_text = get_latest_transcription()
        today_str = datetime.utcnow().strftime("%Y-%m-%d")

        has_today = date_str == today_str and transcription_text

        # 3) Build messages
        if has_today:
            email_subject = "Today's Color Code Announcement"
            email_body = (
                f"Hello {full_name},\n\n"
                f"Here is today's color code announcement for {testing_center}:\n\n"
                f"{transcription_text}\n\n"
                "This message was automatically generated by ColorCodely."
            )
            sms_body = (
                f"ColorCodely - Today's color code for {testing_center}: "
                f"{transcription_text}"
            )
        else:
            email_subject = "Welcome to ColorCodely"
            email_body = (
                f"Hello {full_name},\n\n"
                f"You're now subscribed to daily color code notifications for {testing_center}.\n"
                "You'll start receiving updates after the next daily call runs.\n\n"
                "Thank you for using ColorCodely."
            )
            sms_body = (
                f"Welcome to ColorCodely! "
                f"You are subscribed for {testing_center}. "
                f"Daily updates will begin after the next run."
            )

        # 4) Send Email + SMS (if email settings / Twilio are configured)
        try:
            send_email(email, email_subject, email_body)
        except Exception as e:
            print("Error sending welcome email:", e)

        try:
            send_sms(cell_number, sms_body)
        except Exception as e:
            print("Error sending welcome SMS:", e)

        return jsonify({"status": "success"}), 200

    except Exception as e:
        print("Error in /submit:", e)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route("/daily-call", methods=["POST"])
def daily_call():
    """
    Triggered once per day (e.g., by a Render cron job).
    Initiates a Twilio call to the Huntsville color code line.
    The call is recorded; Twilio will later POST to /twilio/recording-complete.
    """
    if not twilio_client:
        return jsonify({"status": "error", "message": "Twilio not configured"}), 500

    if not BASE_URL:
        return jsonify({"status": "error", "message": "APP_BASE_URL not set"}), 500

    try:
        callback_url = f"{BASE_URL}/twilio/recording-complete"

        call = twilio_client.calls.create(
            to=HUNTSVILLE_COLOR_LINE,
            from_=TWILIO_FROM,
            record=True,
            recording_status_callback=callback_url,
            recording_status_callback_method="POST",
        )

        print("Daily call started, Call SID:", call.sid)
        return jsonify({"status": "started", "call_sid": call.sid}), 200

    except Exception as e:
        print("Error starting daily call:", e)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route("/twilio/recording-complete", methods=["POST"])
def twilio_recording_complete():
    """
    Twilio recording status callback endpoint.
    Twilio will POST recording info here after the call.

    For Twilio Transcription to be included, you may need to enable it
    in Twilio's console or call flow. If available, Twilio sends:
      - RecordingUrl
      - RecordingSid
      - TranscriptionText (depending on configuration)

    Here we:
      1. Extract transcription text (if available)
      2. Save it to DailyTranscriptions
      3. Notify all subscribers by email + SMS
    """
    try:
        form = request.form
        print("Twilio recording callback received:", dict(form))

        # Try to get transcription text (Twilio-side configuration dependent)
        transcription_text = form.get("TranscriptionText")

        recording_url = form.get("RecordingUrl")
        recording_sid = form.get("RecordingSid")

        if not transcription_text:
            # Fallback placeholder if Twilio isn't sending transcription yet
            transcription_text = (
                "Daily color-code announcement recorded. "
                "Transcription not available in this test configuration."
            )

        # Save the transcription for today
        today_str = datetime.utcnow().strftime("%Y-%m-%d")
        save_daily_transcription(transcription_text, today_str)

        # Notify all subscribers
        subscribers = get_all_subscribers()

        for sub in subscribers:
            full_name = sub.get("full_name") or "Subscriber"
            email = sub.get("email")
            cell = sub.get("cell_number")
            testing_center = sub.get("testing_center") or "your testing center"

            email_subject = "Today's Color Code Announcement"
            email_body = (
                f"Hello {full_name},\n\n"
                f"Here is today's color code announcement for {testing_center}:\n\n"
                f"{transcription_text}\n\n"
                "This message was automatically generated by ColorCodely.\n\n"
                f"(Recording URL: {recording_url or 'N/A'})"
            )
            sms_body = (
                f"ColorCodely - Today's color code for {testing_center}: "
                f"{transcription_text}"
            )

            if email:
                try:
                    send_email(email, email_subject, email_body)
                except Exception as e:
                    print(f"Error sending email to {email}:", e)

            if cell:
                try:
                    send_sms(cell, sms_body)
                except Exception as e:
                    print(f"Error sending SMS to {cell}:", e)

        return jsonify({"status": "ok"}), 200

    except Exception as e:
        print("Error in /twilio/recording-complete:", e)
        return jsonify({"status": "error", "message": str(e)}), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
